export const USER_LOGIN = 'USER_LOGIN';
export const USER_CREATION_ERROR = 'USER_CREATION_ERROR';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_PLACES = 'GET_ALL_PLACES';
export const DELETE_PLACE = 'DELETE_PLACE';